name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  composer-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: composer install --ansi --no-progress --no-interaction --prefer-dist
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r NanitRobotsBoards.zip Nanit
      - uses: actions/upload-artifact@v2
        with:
          name: NanitRobotsBoards.zip
